version: 2
updates:
  - package-ecosystem: "pip"
    directory: "/"
    schedule:
      interval: "daily"
    target-branch: "v2"
    labels:
      - "dependencies"
    allow:
      - dependency-name: "PyInstaller"
      - dependency-name: "flit_core"
      - dependency-name: "colorama"
      - dependency-name: "docutils"
